# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Terminal one
    init: sudo apt-get update -q && sudo apt-get upgrade && sudo apt install ncdu ffmpeg tmux # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
    command: pip3 install ffmpeg-python telethon wget gevent requests validators

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
