# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Terminal one
    init: sudo apt-get update -y && sudo apt-get upgrade -y && sudo apt install python3-pip zsh ncdu ffmpeg tmux -y && pip3 install -r requirements.txt # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
    command: python3 tele2.py

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
